### ISSUE TITLE
PowerBi instructionals

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [marcingminski/sqlwatch-docs#4]
Please can this page https://docs.sqlwatch.io/configuration/user-configuration/powerbi-report-parameters have some information to say that you should and how to change the parameters so that beardy fellows dont go blindly down wondering why its not working as expected when they change the data source ;-)

**Comment by marcingminski** [comment]
Yes sir, this has already been mentioned to me that it’s not obvious in the docs. I will try to get it all sorted before 2.2 release. Thank you trying it!

**Comment by marcingminski** [comment]
I have been working on some improvements recently: can you take a look when you get a chance and provide feedback please? https://docs.sqlwatch.io/v/2.2/
Thanks
