### ISSUE TITLE
SSIS instructionals

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [marcingminski/sqlwatch-docs#5]
Please may this page https://docs.sqlwatch.io/configuration/data#central-repository-collector

have a little more about how to set up. I knwo every environment is different but a brand new user would not know where to start

Also, and explanation or maybe example of the timings of the jobs here would be good, as well as a link to https://docs.sqlwatch.io/configuration/user-configuration#central-repository-configuration as if you dont have any instances in that table you dont get any data!!

**Comment by marcingminski** [comment]
Noted. I’ll update it. Thank you! I’m liking this feedback, please give more. I’m aware there are gaps in the docs.

**Comment by marcingminski** [comment]
Some improvements to SSIS instructions: https://docs.sqlwatch.io/v/2.2/central-repository/requirements
