### ISSUE TITLE
SQLWATCH-LOGGER-DISK-UTILISATION fails when data compression is on/off for multiple partitions

### ISSUE THREAD

**Issue by mmaagk642** [marcingminski/sqlwatch-docs#8]
When running SQLWATCH-LOGGER-DISK-UTILISATION job, it will fail on last step, and error message is:

![image](https://user-images.githubusercontent.com/29732321/75985190-d8f33680-5eb9-11ea-85b5-5dd041569a6e.png)

This is due to fact that multiple partitions are existent within same table, but some are compressed and some are not. 

query used to find this issue below

select database_name from vw_sqlwatch_report_dim_database where sqlwatch_database_id = 6
--USE database_returned_above
select 
	mt.sqlwatch_database_id,
	mt.sqlwatch_table_id,
	row_count = convert(real,avg(p.rows)),
	total_pages = convert(real,sum(a.total_pages)),
	used_pages = convert(real,sum(a.used_pages)),
	p.[data_compression],
	@@SERVERNAME,
	row_count_delta = convert(real,isnull(avg(p.rows) - max(dt.row_count),0)),
	total_pages_delta = convert(real,isnull(sum(a.total_pages) - max(dt.total_pages),0)),
	used_pages_delta = convert(real,isnull(sum(a.used_pages) - max(dt.used_pages),0))
from sys.tables t
inner join sys.indexes i on t.object_id = i.object_id
inner join sys.partitions p on i.object_id = p.object_id AND i.index_id = p.index_id
inner join sys.allocation_units a on p.partition_id = a.container_id
inner join sys.schemas s on t.schema_id = s.schema_id
inner join sys.databases sdb on sdb.name = DB_NAME()
inner join [SQLWATCH].[dbo].[sqlwatch_meta_database] mdb
	on mdb.database_name = sdb.name collate database_default
	and mdb.database_create_date = sdb.create_date
	and mdb.sql_instance = @@SERVERNAME
	and mdb.sqlwatch_database_id = 6
inner join [SQLWATCH].[dbo].[sqlwatch_meta_table] mt
	on mt.table_name = s.name + '.' + t.name collate database_default
	and mt.sqlwatch_database_id = mdb.sqlwatch_database_id
	and mt.sql_instance = mdb.sql_instance
	and mt.sqlwatch_table_id = 344
left join [SQLWATCH].[dbo].[sqlwatch_logger_disk_utilisation_table] dt
	on dt.sqlwatch_database_id = mdb.sqlwatch_database_id
	and dt.sql_instance = mdb.sql_instance
	and dt.sqlwatch_table_id = mt.sqlwatch_table_id
	and dt.snapshot_time = (select max(snapshot_time) from sqlwatch_logger_snapshot_header where snapshot_type_id = 22)
group by mt.sqlwatch_database_id, mt.sqlwatch_table_id, p.[data_compression]

this will show the compressed and not compressed partitions in same table

**Comment by marcingminski** [comment]
Hi, sorry this was missed but its the wrong repository. This repo is for the SQLWATCH documentation, not for the SQLWATCH application itself. I believe this issue has already been fixed, could you try the latest version, please?
